BUG: Fix problem with default basedir
If the base data directory was not set, a default one would be selected,
by using '..' to refer to a directory below, which in turn would
inconsistently flag users as lacking permissions:

```
QiitaPetAuthorizationError: User demo@microbio.me is not authorized to
access
/Users/yoshikivazquezbaeza/.virtualenvs/qiita-0.2.0-rc1/lib/python2.7/site-packages/qiita_db/support_files/test_data/job/1_summarize_taxa_through_plots.py_output_dir/taxa_summary_plots/bar_charts.html
```

Although the paths were the same, this is verified through string
matching thus 'lol/foo/../jk' and 'lol/jk' would not match (see example
structure below) even though they refer to the same folder:

lol/
├── foo
│   └── file.txt
├── jk
└── plel